name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for submitting your first issue to this repository!'
        pr-message: 'Thanks for submitting your first PR to this repository. We appreciate your contribution! Our team will review your code within 3 business days. We <3 open source and are so glad you do, too!'
